'use client';

import { type FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

type Draft = { name: string; campaign_type: string; destination_requirement: string; call_to_action: string; placement_ideas: string[]; tracking_plan: string[]; rationale: string };
export default function AIAssistant({ actions, canApprove }: { actions: Array<{ id: string; action_type: string; action_payload: { campaign_id?: string }; status: string; created_at: string }>; canApprove: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [draft, setDraft] = useState<Draft | null>(null);
  async function insights() { setBusy('insights'); const response = await fetch('/api/ai/insights', { method: 'POST' }); const body = await response.json().catch(() => ({})); setBusy(''); setMessage(response.ok ? body.executive_summary : body.error || 'Could not generate insights.'); if (response.ok) router.refresh(); }
  async function campaignDraft(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy('draft'); const form = new FormData(event.currentTarget); const response = await fetch('/api/ai/drafts', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ goal: form.get('goal') }) }); const body = await response.json().catch(() => ({})); setBusy(''); if (!response.ok) return setMessage(body.error || 'Could not generate a campaign draft.'); setDraft(body); setMessage('Draft generated from authorized workspace context. Review it before creating a campaign.'); }
  async function review(id: string, decision: 'approved' | 'rejected') { setBusy(id); const response = await fetch(`/api/ai/actions/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ decision }) }); const body = await response.json().catch(() => ({})); setBusy(''); setMessage(response.ok ? `Action ${body.status}.` : body.error || 'Could not review the action.'); router.refresh(); }
  return <div className="stack"><section className="ai-command-grid"><article className="card ai-command"><div className="eyebrow">Evidence-grounded report</div><h2>Analyze the last 30 days</h2><p className="muted">Generate stored insights and recommendations from canonical scans, campaigns, and locations.</p><button className="btn" disabled={Boolean(busy)} onClick={insights}>{busy === 'insights' ? 'Analyzing...' : 'Generate business insights'}</button></article><article className="card ai-command"><div className="eyebrow">Structured campaign draft</div><h2>Turn a goal into a plan</h2><form onSubmit={campaignDraft}><textarea className="input" name="goal" minLength={10} maxLength={500} required rows={4} placeholder="Improve restaurant reviews from table traffic without confusing a scan with a conversion." /><button className="btn" disabled={Boolean(busy)}>{busy === 'draft' ? 'Drafting...' : 'Generate campaign draft'}</button></form></article></section>{message && <p className="notice" role="status">{message}</p>}{draft && <section className="card draft-card"><span className="pill">Draft only</span><h2>{draft.name}</h2><p>{draft.rationale}</p><div className="draft-grid"><div><h3>Destination requirement</h3><p>{draft.destination_requirement}</p><h3>Call to action</h3><p>{draft.call_to_action}</p></div><div><h3>Placement ideas</h3><ul>{draft.placement_ideas.map((item) => <li key={item}>{item}</li>)}</ul><h3>Tracking plan</h3><ul>{draft.tracking_plan.map((item) => <li key={item}>{item}</li>)}</ul></div></div><a className="btn" href={`/dashboard/new?type=${encodeURIComponent(draft.campaign_type)}`}>Open campaign builder</a></section>}<section className="card table-card"><div className="sectionhead"><div><h2>Proposed actions</h2><p className="muted">AI output cannot mutate campaigns. An owner or admin must approve each supported action.</p></div></div>{actions.length ? <div className="data-table"><div className="data-row data-head"><span>Action</span><span>Campaign</span><span>Status</span><span>Review</span></div>{actions.map((action) => <div className="data-row" key={action.id}><b>{action.action_type.replaceAll('_', ' ')}</b><code>{action.action_payload?.campaign_id?.slice(0, 8) || 'n/a'}</code><span className={`status ${action.status}`}>{action.status}</span><span className="rowactions">{canApprove && action.status === 'proposed' && <><button className="mini" disabled={busy === action.id} onClick={() => review(action.id, 'approved')}>Approve</button><button className="mini danger" disabled={busy === action.id} onClick={() => review(action.id, 'rejected')}>Reject</button></>}</span></div>)}</div> : <p className="muted">No consequential actions have been proposed.</p>}</section></div>;
}
